### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by djannot** [tzolov/vagrant-pivotalhd#16]
I get the following error. Is there any issue with the Vagrant box ?

# vagrant up
CLUSTER NAME: PHD30C1 
BLUEPRINT NAME: all-services-blueprint 
STACK: PHD-3.0 
BLUEPRINT FILE: phd-all-services-blueprint.json 
HOST-MAPPING FILE: 4-node-all-services-hostmapping.json 
Ambari Provision Script: provision/phd_install_ambari.sh
Number of cluster nodes (excluding Ambari): 3 
Bringing machine 'phd1' up with 'virtualbox' provider...
Bringing machine 'phd2' up with 'virtualbox' provider...
Bringing machine 'phd3' up with 'virtualbox' provider...
Bringing machine 'ambari' up with 'virtualbox' provider...
==> phd1: Box 'bigdata/centos6.4_x86_64' could not be found. Attempting to find and install...
    phd1: Box Provider: virtualbox
    phd1: Box Version: >= 0
==> phd1: Loading metadata for box 'bigdata/centos6.4_x86_64'
    phd1: URL: https://atlas.hashicorp.com/bigdata/centos6.4_x86_64
==> phd1: Adding box 'bigdata/centos6.4_x86_64' (v1.0.0) for provider: virtualbox
    phd1: Downloading: https://atlas.hashicorp.com/bigdata/boxes/centos6.4_x86_64/versions/1.0.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

**Comment by tzolov** [comment]
@djannot thanks for the feedback. It seems you have stumbled upon a network connectivity issue. Perhaps firewall or some other network settings?
By the way i've just updated the VBox to centos6.6 and download address backing it more reliable. You can update and give it atry
