### ISSUE TITLE
All VMs have IPTABLES active in VMware Fusion version

### ISSUE THREAD

**Issue by dbbaskette** [tzolov/vagrant-pivotalhd#5]
iptables is active, so the clients can't connect to the local http server to install the ambari agents

**Comment by dbbaskette** [comment]
I fixed by adding
 /etc/init.d/iptables stop   
chkconfig iptables off

to the preparehosts.sh script.

**Comment by tzolov** [comment]
Nice spot @dbbaskette ! Would mind opening a pull request (and get the credit for the patch ;)

**Comment by tzolov** [comment]
Just checked the spect: http://pivotalhd.docs.pivotal.io/docs/install-ambari.html#prepare 
Apparently all prerequisite steps are missing:  1.5 Disable or Configure iptables, 1.6 Disable SELinux and PackageKit and Check umask Value, 1.7 Disable IPv6, 1.8 Disable Transparent Huge Pages (THP)
Some of those steps are not necessary with the default VBox but can suffice if someone decided to use a different vbox.

**Comment by dbbaskette** [comment]
Still want me to do the pull, or did you go ahead since out hours are so much different?   SELinux was disabled.....so to get it running iptables was all that i had to change.    THP is probably optional in this type environment....umask I didn't check

**Comment by tzolov** [comment]
please go ahead and pull

**Comment by tzolov** [comment]
Resolved by 11da148bbddaee417515a48ffbb811cc76d32cc6
