### ISSUE TITLE
Vagrant job shows Ambari URL to monitor status, but IP is required.

### ISSUE THREAD

**Issue by dbbaskette** [tzolov/vagrant-pivotalhd#6]
This should report the Ambari IP address:

echo "Open http://$AMBARI_HOSTNAME:8080 (user:admin, pass: admin) to monitor the installation progress"

An alternative would be to use https://github.com/smdahlen/vagrant-hostmanager which I have used in my Vagrant clusters in the past.   It adds all the cluster hostnames/ips to your local machines /etc/hosts file.

**Comment by tzolov** [comment]
Thanks, I've noticed this yesterday. I will commit the Ambari IP as an easy fix but will check the host manager. At the moment i've hardcoded the host names on my laptop so the host manager would be a flexible alternative
